#!/usr/bin/env python3
"""Capture actual game code using PRG32's software renderer on the host."""
import os
from pathlib import Path
import re
import subprocess
import tempfile
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
FRAMEWORK = Path(os.environ.get('PRG32_ROOT', ROOT.parent / 'PRG32')).resolve()


def function(source, name):
    """Extract a top-level upstream function, whose closing brace starts a line."""
    match = re.search(r'^(?:static )?[^\n;{}]*\b' + name +
                      r'\([^;{}]*\)\s*\{.*?\n\}', source, re.M | re.S)
    if not match:
        raise ValueError(f'Cannot locate upstream renderer function {name}')
    return match.group(0)


def renderer_source():
    """Return annotated host renderer excerpts for still or video capture."""
    display = (FRAMEWORK / 'components/prg32/prg32_display_qemu_rgb.c').read_text()
    sprites = (FRAMEWORK / 'components/prg32/prg32_sprite.c').read_text()
    font = re.search(r'static const uint8_t g_font8\[96\]\[8\].*?\n};', display, re.S).group(0)
    font = font.replace(' PRG32_FLASH_RODATA', '')
    # Reuse upstream rasterization and font data without linking device drivers.
    renderer = ['#include "prg32.h"', '#define PRG32_VIEWPORT_Y 20',
                'static uint16_t g_fb[PRG32_LCD_W*PRG32_LCD_H];',
                'static int g_fullscreen, g_band_color_set, g_band_area_valid;',
                'static uint16_t g_band_color, g_last_band_color;',
                'static int g_band_cache_valid[2];',
                'static int g_dirty_x0,g_dirty_y0,g_dirty_x1,g_dirty_y1;', font]
    for name in ['dirty_add_raw', 'logical_h', 'logical_y_to_raw', 'dirty_add',
                 'font_glyph', 'fill_raw_rect', 'prg32_gfx_clear', 'prg32_gfx_pixel',
                 'prg32_gfx_rect', 'prg32_gfx_text8']:
        renderer.append(function(display, name))
    renderer.append(function(sprites, 'prg32_sprite_draw_frame'))
    generated = '\n'.join(renderer)
    annotated = '\n'.join('// EDUCATIONAL: Upstream PRG32 software rendering excerpt; generated by tools/capture_screen.py.\n' + line
                          if line.strip() else line for line in generated.splitlines())
    return annotated + '\n'


def main():
    annotated = renderer_source()
    with tempfile.TemporaryDirectory(prefix='vega-capture-') as temporary:
        directory = Path(temporary)
        (directory / 'capture_renderer.h').write_text(annotated + '\n')
        executable = directory / 'capture'
        subprocess.run([os.environ.get('CC', 'cc'), '-std=c99', '-Wall', '-Wextra', '-Werror',
                        '-fsanitize=address,undefined', '-I', str(directory),
                        '-I', str(FRAMEWORK / 'components/prg32/include'),
                        '-I', str(FRAMEWORK / 'components/prg32_audio/include'),
                        str(ROOT / 'tests/capture_game.c'), '-o', str(executable)], check=True)
        ppm = subprocess.check_output([str(executable)])
        raw = directory / 'screen.ppm'
        raw.write_bytes(ppm)
        out = ROOT / 'assets/gameplay.png'
        with Image.open(raw) as screen:
            # An integer nearest-neighbor enlargement preserves every game pixel.
            screen.resize((960, 600), Image.Resampling.NEAREST).save(out)
        print(out)


if __name__ == '__main__':
    main()
